-- Demo orders + invoices for admin user
-- Email used: admin@yakiwood.lt

WITH order_one AS (
  INSERT INTO orders (
    order_number,
    customer_email,
    customer_name,
    customer_phone,
    customer_address,
    items,
    subtotal,
    vat_amount,
    total,
    currency,
    status,
    payment_status,
    created_at,
    updated_at
  ) VALUES (
    'YW-2026-0101',
    'admin@yakiwood.lt',
    'Admin User',
    '+37060000009',
    'Laisves al. 10, Kaunas, LT-44250, Lietuva',
    '[{"id":"item-1","name":"Shou sugi ban lentos (maumedis)","quantity":6,"basePrice":18.0,"configuration":{"thicknessMm":20,"widthMm":140,"lengthMm":3000}}]',
    108.00,
    22.68,
    130.68,
    'EUR',
    'completed',
    'paid',
    NOW() - INTERVAL '12 days',
    NOW() - INTERVAL '12 days'
  )
  ON CONFLICT (order_number) DO NOTHING
  RETURNING id, customer_email, customer_name, customer_phone, customer_address, subtotal, vat_amount, total
),
order_two AS (
  INSERT INTO orders (
    order_number,
    customer_email,
    customer_name,
    customer_phone,
    customer_address,
    items,
    subtotal,
    vat_amount,
    total,
    currency,
    status,
    payment_status,
    created_at,
    updated_at
  ) VALUES (
    'YW-2026-0102',
    'admin@yakiwood.lt',
    'Admin User',
    '+37060000009',
    'Laisves al. 10, Kaunas, LT-44250, Lietuva',
    '[{"id":"item-1","name":"Shou sugi ban lentos (eglė)","quantity":10,"basePrice":11.5,"configuration":{"thicknessMm":20,"widthMm":120,"lengthMm":2400}}]',
    115.00,
    24.15,
    139.15,
    'EUR',
    'processing',
    'pending',
    NOW() - INTERVAL '4 days',
    NOW() - INTERVAL '4 days'
  )
  ON CONFLICT (order_number) DO NOTHING
  RETURNING id, customer_email, customer_name, customer_phone, customer_address, subtotal, vat_amount, total
)
INSERT INTO invoices (
  invoice_number,
  order_id,
  seller_name,
  seller_company_code,
  seller_vat_code,
  seller_address,
  seller_city,
  seller_postal_code,
  seller_country,
  seller_phone,
  seller_email,
  seller_bank_name,
  seller_bank_account,
  buyer_name,
  buyer_company_name,
  buyer_company_code,
  buyer_vat_code,
  buyer_address,
  buyer_city,
  buyer_postal_code,
  buyer_country,
  buyer_phone,
  buyer_email,
  items,
  subtotal,
  vat_amount,
  total,
  currency,
  status,
  issued_at,
  due_date,
  payment_method,
  created_at,
  updated_at
)
SELECT
  'SF-2026-0101',
  order_one.id,
  'UAB Yakiwood',
  '123456789',
  'LT123456789',
  'Kauno g. 1',
  'Kaunas',
  'LT-44100',
  'Lietuva',
  '+37060000000',
  'info@yakiwood.lt',
  'Swedbank',
  'LT12 7300 0100 0000 0000',
  order_one.customer_name,
  NULL,
  NULL,
  NULL,
  'Laisves al. 10',
  'Kaunas',
  'LT-44250',
  'Lietuva',
  order_one.customer_phone,
  order_one.customer_email,
  '[{"id":"item-1","name":"Shou sugi ban lentos (maumedis)","quantity":6,"unitPrice":18.0,"vatRate":0.21,"total":108}]',
  order_one.subtotal,
  order_one.vat_amount,
  order_one.total,
  'EUR',
  'paid',
  NOW() - INTERVAL '11 days',
  NOW() - INTERVAL '3 days',
  'bank_transfer',
  NOW() - INTERVAL '11 days',
  NOW() - INTERVAL '11 days'
FROM order_one
WHERE order_one.id IS NOT NULL
ON CONFLICT (invoice_number) DO NOTHING;

INSERT INTO invoices (
  invoice_number,
  order_id,
  seller_name,
  seller_company_code,
  seller_vat_code,
  seller_address,
  seller_city,
  seller_postal_code,
  seller_country,
  seller_phone,
  seller_email,
  seller_bank_name,
  seller_bank_account,
  buyer_name,
  buyer_company_name,
  buyer_company_code,
  buyer_vat_code,
  buyer_address,
  buyer_city,
  buyer_postal_code,
  buyer_country,
  buyer_phone,
  buyer_email,
  items,
  subtotal,
  vat_amount,
  total,
  currency,
  status,
  issued_at,
  due_date,
  payment_method,
  created_at,
  updated_at
)
SELECT
  'SF-2026-0102',
  order_two.id,
  'UAB Yakiwood',
  '123456789',
  'LT123456789',
  'Kauno g. 1',
  'Kaunas',
  'LT-44100',
  'Lietuva',
  '+37060000000',
  'info@yakiwood.lt',
  'Swedbank',
  'LT12 7300 0100 0000 0000',
  order_two.customer_name,
  NULL,
  NULL,
  NULL,
  'Laisves al. 10',
  'Kaunas',
  'LT-44250',
  'Lietuva',
  order_two.customer_phone,
  order_two.customer_email,
  '[{"id":"item-1","name":"Shou sugi ban lentos (eglė)","quantity":10,"unitPrice":11.5,"vatRate":0.21,"total":115}]',
  order_two.subtotal,
  order_two.vat_amount,
  order_two.total,
  'EUR',
  'issued',
  NOW() - INTERVAL '3 days',
  NOW() + INTERVAL '10 days',
  'bank_transfer',
  NOW() - INTERVAL '3 days',
  NOW() - INTERVAL '3 days'
FROM order_two
WHERE order_two.id IS NOT NULL
ON CONFLICT (invoice_number) DO NOTHING;
